EVA-2770 - Script to gather per-species rs counts
EBIvariation/eva-tasks pull request #62
Opened 2022-02-22 16:01 UTC by apriltuesday

2022-02-23 08:09 UTC, tcezard requested changes

2022-02-23 09:11 UTC, apriltuesday commented on tasks/eva_2770/gather_per_species_clustering_counts.py
> +        f'bsub {os.path.join(shell_script_dir, script_name)} {species_dir} {metric_id}'
Yes of course, thanks for catching!

2022-02-23 09:15 UTC, tcezard approved these changes

2022-02-28 09:30 UTC, andresfsilva approved these changes

2022-02-28 10:16 UTC, merged